openapi: 3.0.0
info:
  title: PROYECTO FINAL DE MODULO
  version: '1.0'
  description: Base de datos avanzadas - Movies
  contact:
    name: ifmm87@gmail.com
servers:
  - url: 'http://localhost:1987'
paths:
  /clientes:
    post:
      summary: Servicio para crear un nuevo cliente
      tags: ['clientes']
      operationId: post-api-v1-clientes
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nombreCompleto:
                  type: string
                  example: 'jose jose'
                nit:
                  type: string
                  example: '12773747843' 
                celular:
                  type: string
                  example: '74958585'
                fechaNacimiento:
                  type: string
                  example: '2000-10-10'
                direccion:
                  type: string
                  example: 'direccion 123'
                latitud:
                  type: string
                  example: '-16,89879879'
                longitud:
                  type: string
                  example: '-67,89879879'
      responses:
        '200':
          description: OK
    get:
      summary: Servicio para recuperar clientes
      tags: ['clientes']
      operationId: get-api-v1-clientes
      responses:
        '200':
          description: OK
  /clientes/{idCliente}:
    get:
      parameters:
        - in: path
          name: idCliente
      summary: Servicio para recuperar 1 cliente
      tags: ['clientes']
      operationId: get-api-v1-clientes-single
      responses:
        '200':
          description: OK
    put:
      parameters:
        - in: path
          name: idCliente
      summary: Servicio para editar 1 cliente
      tags: ['clientes']
      operationId: get-api-v1-clientes-single
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nombreCompleto:
                  type: string
                  example: 'jose jose'
                nit:
                  type: string
                  example: '12773747843' 
                celular:
                  type: string
                  example: '74958585'
                fechaNacimiento:
                  type: string
                  example: '2000-10-10'
                direccion:
                  type: string
                  example: 'direccion 123'
                latitud:
                  type: string
                  example: '-16,89879879'
                longitud:
                  type: string
                  example: '-67,89879879'
      responses:
        '200':
          description: OK
    delete:
      parameters:
        - in: path
          name: idCliente
      summary: Servicio para eliminar 1 cliente
      tags: ['clientes']
      operationId: get-api-v1-clientes-single
      responses:
        '200':
          description: OK
  /clientes/{idCliente}/bloquear:
    patch:
      parameters:
        - in: path
          name: idCliente
      summary: Servicio para bloquear 1 cliente
      tags: ['clientes']
      operationId: get-api-v1-clientes-single
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                motivoBloqueo:
                  type: string
                  example: 'bloqueado,no devolvio'
      responses:
        '200':
          description: OK
  /clientes/{idCliente}/desbloquear:
    patch:
      parameters:
        - in: path
          name: idCliente
      summary: Servicio para desbloquear 1 cliente
      tags: ['clientes']
      operationId: get-api-v1-clientes-single
      responses:
        '200':
          description: OK
  /clientes/{idCliente}/historial:
    get:
      parameters:
        - in: path
          name: idCliente
      summary: Servicio para bloquear 1 cliente
      tags: ['clientes']
      operationId: get-api-v1-clientes-single
      responses:
        '200':
          description: OK
  
  /videos:
    post:
      summary: Servicio para crear un nuevo video
      tags: ['videos']
      operationId: post-api-v1-videos
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                  example: 'Sleepy Hollow'
                genero:
                  type: array
                  items:
                    type: string
                    example: 'Terror'
                duracion:
                  type: string
                  example: '230'
                costoUnitario:
                  type: string
                  example: 78.9
                copias:
                  type: string
                  example: 5
                anioPublicacion:
                  type: number
                  example: 2005
                reparto:
                  type: array
                  items:
                    type:string
                  example: ["Jhonny Deep", "Cristina Picci"]
      responses:
        '200':
          description: OK
    get:
      summary: Servicio para recuperar videos
      tags: ['videos']
      operationId: get-api-v1-vieos
      responses:
        '200':
          description: OK
  /videos/{idVideo}:
    get:
      parameters:
        - in: path
          name: idVideo
      summary: Servicio para recuperar 1 video
      tags: ['videos']
      operationId: get-api-v1-videos-single
      responses:
        '200':
          description: OK
    put:
      parameters:
        - in: path
          name: idVideo
      summary: Servicio para editar 1 video
      tags: ['videos']
      operationId: get-api-v1-clientes-videos
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                  example: 'Sleepy Hollow'
                genero:
                  type: array
                  items:
                    type: string
                    example: 'Terror'
                duracion:
                  type: string
                  example: '230'
                costoUnitario:
                  type: string
                  example: 78.9
                copias:
                  type: string
                  example: 5
                reparto:
                  type: array
                  items:
                    type:string
                  example: ["Jhonny Deep", "Cristina Picci"]
      responses:
        '200':
          description: OK
    delete:
      parameters:
        - in: path
          name: idVideo
      summary: Servicio para eliminar 1 video
      tags: ['videos']
      operationId: get-api-v1-videos-single-del
      responses:
        '200':
          description: OK
  /videos/{idVideo}/alta:
    patch:
      parameters:
        - in: path
          name: idVideo
      summary: Servicio para dar de alta una copia
      tags: ['videos']
      operationId: get-api-v1-clientes-single
      responses:
        '200':
          description: OK
  /videos/{idVideo}/baja:
    patch:
      parameters:
        - in: path
          name: idVideo
      summary: Servicio para dar de baja 1 copia
      tags: ['videos']
      operationId: get-api-v1-clientes-single
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                motivo:
                  type: string
                  example: ' Baja, no devolvio'
      responses:
        '200':
          description: OK

  /prestamos:
    post:
      summary: Servicio para crear un prestamo de video
      tags: ['prestamos']
      operationId: post-api-v1-videos
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente:
                  type: string
                  example: '000000000000000000000001'
                videos:
                  type: array
                  items:
                    type: string
                  example:  [ "6095c80efc36d5432983dd2b", "569190cc24de1e0ce2dfcd59", "569190cc24de1e0ce2dfcd5b" ]
                fechaDevolucion:
                  type: string
                  example: "2021-05-01"
                diasPrestamo:
                  type: number
                  example: 3
      responses:
        '200':
          description: OK
    get:
      summary: Servicio para recuperar prestamos
      tags: ['prestamos']
      operationId: get-api-v1-vieos
      responses:
        '200':
          description: OK
  /prestamos/{idPrestamo}:
    get:
      parameters:
        - in: path
          name: idPrestamo
      summary: Servicio para recuperar 1 prestamo
      tags: ['prestamos']
      operationId: get-api-v1-videos-single
      responses:
        '200':
          description: OK
    put:
      parameters:
        - in: path
          name: idPrestamo
      summary: Servicio para editar 1 prestamo
      tags: ['prestamos']
      operationId: get-api-v1-prestamos
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente:
                  type: string
                  example: '000000000000000000000001'
                videos:
                  type: array
                  items:
                    type: string
                  example:  [ "6095c80efc36d5432983dd2b", "569190cc24de1e0ce2dfcd59", "569190cc24de1e0ce2dfcd5b" ]
                fechaDevolucion:
                  type: string
                  example: "2021-05-01"
                diasPrestamo:
                  type: number
                  example: 3
      responses:
        '200':
          description: OK
    delete:
      parameters:
        - in: path
          name: idPrestamo
      summary: Servicio para eliminar 1 prestamo
      tags: ['prestamos']
      operationId: get-api-v1-videos-prestamo-del
      responses:
        '200':
          description: OK
  /prestamos/devueltos:
    get:
      summary: Servicio para listar devueltos
      tags: ['prestamos']
      operationId: get-api-v1-prestamos-devuelot
      responses:
        '200':
          description: OK
  /prestamos/pendientes:
    get:
      summary: Servicio para listar pendientes
      tags: ['prestamos']
      operationId: get-api-v1-prestamos-pendientes
      responses:
        '200':
          description: OK
  /prestamos/infractores:
    get:
      summary: Servicio para listar infractores
      tags: ['prestamos']
      operationId: get-api-v1-prestamos-infractores
      responses:
        '200':
          description: OK
  /prestamos/ranking:
    get:
      summary: Servicio para listar ranking
      tags: ['prestamos']
      operationId: get-api-v1-prestamos-ranking
      responses:
        '200':
          description: OK
